#!/bin/sh 

java -jar target/selectboard-0.0.1-SNAPSHOT.jar --server.port=8080 --server.host=localhost --apiHttps=false --SIGNUP_WAIT=20 --HINT_VIEW_WAIT=60 --ANSWER_WAIT=60 --ANSWER_SUBMIT_WAIT=60 --ANSWER_VALIDATE_WAIT=60 --ANSWER_SHOW_WAIT=10 --ANSWER_SHOW_WAIT=10 --MAX_ROUNDS=2
#java -jar target/selectboard-0.0.1-SNAPSHOT.jar --server.port=8080 --server.host=192.168.1.135 --SIGNUP_WAIT=20 --HINT_VIEW_WAIT=60 --ANSWER_WAIT=60 --ANSWER_SUBMIT_WAIT=60 --ANSWER_VALIDATE_WAIT=60 --ANSWER_SHOW_WAIT=10 --ANSWER_SHOW_WAIT=10 --MAX_ROUNDS=2
